name: 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: 

    steps:
    - uses: 
    - name: 
      uses: 
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 

    - name: 
      run: 
    - name: 
      run: 
